# Generated by Django 5.2.12 on 2026-03-05 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jarvis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('name', models.CharField()),
                ('title', models.CharField()),
                ('link', models.CharField()),
                ('text', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
